### ISSUE TITLE
Allow easier configuration of custom AWSCredentialsProviders

### ISSUE THREAD

**Issue by DarkAtra** [spring-cloud/spring-cloud-aws#493] opened 2019-09-16 20:05 UTC
I want to configure my application to use a custom AWSCredentialsProvider.

Usually i would expect an auto configuration to consider bean definitions and use defaults only if no bean of a specific type was found. So as a user i'd expect the following code to successfully register a custom `AWSCredentialsProvider`:

```
@Bean
public AWSCredentialsProvider awsCredentialsProvider() {
	return new CustomAWSCredentialsProvider();
}
```

However the auto configuration still decides to configure it's own AWSCredentialsProvider bean.

It seems like you have to provide a bean with the following names to make it work:
```
@Bean(name = {CredentialsProviderFactoryBean.CREDENTIALS_PROVIDER_BEAN_NAME, AmazonWebserviceClientConfigurationUtils.CREDENTIALS_PROVIDER_BEAN_NAME} )
public AWSCredentialsProvider awsCredentialsProvider() {
	return new CustomAWSCredentialsProvider();
}
```

Inspecting the constants provided above i just noticed that they differ in value but still use the same name and are also used interchangeably* across the whole project. Wouldn't it make more sense to have one constant (e.g. one bean name) in order to provide a custom credentials provider.

Whats the idea behind using 2 bean names for the same thing? Or am i getting something wrong and they are used for different purposes?

\* to be confirmed :D

**Comment by maciejwalkowiak** [comment] 2020-06-06 08:35
Agreed credentials provider should be easily replaceable with user provided bean.

**Comment by maciejwalkowiak** [comment] 2020-06-06 19:50
Closing as a duplicate of #102

**Closed by maciejwalkowiak** 2020-06-06 19:50 UTC
Labels: component: core, type: enhancement
