### ISSUE TITLE
Changed values in Secrets manager dont reflect in application till it is restarted

### ISSUE THREAD

**Issue by damvinod** [spring-cloud/spring-cloud-aws#480] opened 2019-07-13 01:14 UTC
I successfully integrated aws secrets manager to spring boot app using spring-cloud-starter-secret-manger.

I observed that if any values are changed in secrets manager they are not reflected in app till it is restarted.

Is there feature to auto refresh the values in app if any key value pair is changed in secrets manager ?

**Comment by bsamartins** [comment] 2019-08-22 07:32
@damvinod I might be mistaken, but I don't think that spring configuration supports automatic context refreshes. You might have to manually restart the app or trigger the `/refresh` endpoint.

From the [documentation](url)

> The RefreshScope is a bean in the context and it has a public method refreshAll() to refresh all beans in the scope by clearing the target cache. There is also a refresh(String) method to refresh an individual bean by name. This functionality is exposed in the /refresh endpoint (over HTTP or JMX).

**Comment by damvinod** [comment] 2019-08-29 14:48
> @damvinod I might be mistaken, but I don't think that spring configuration supports automatic context refreshes. You might have to manually restart the app or trigger the `/refresh` endpoint.
> 
> From the [documentation](url)
> 
> > The RefreshScope is a bean in the context and it has a public method refreshAll() to refresh all beans in the scope by clearing the target cache. There is also a refresh(String) method to refresh an individual bean by name. This functionality is exposed in the /refresh endpoint (over HTTP or JMX).

Thanks Will try to explore the RefreshScope

**Comment by gustavomonarin** [comment] 2019-09-04 14:05
@damvinod which triggers the secret change? are u using RotationRules or changing it manually?

**Comment by maciejwalkowiak** [comment] 2020-11-25 00:11
Duplicate of https://github.com/spring-cloud/spring-cloud-aws/issues/624

**Closed by maciejwalkowiak** 2020-11-25 00:11 UTC
Labels: component: secrets-manager, status: duplicate, type: enhancement
