### ISSUE TITLE
Spring Cloud service won't start when cloud:spring-cloud-starter-aws-messaging is included.

### ISSUE THREAD

**Issue by ch4dwick** [spring-cloud/spring-cloud-aws#508] opened 2019-11-13 03:01 UTC
Hoxton.BUILD-SNAPSHOT (also happens in RC1)
Spring Boot 2.2.0.BUILD-SNAPSHOT (also happens in M3)

When trying out the code below I get an java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy during startup

Steps to reproduce:

build.gradle
```
plugins {
	id 'org.springframework.boot' version '2.2.1.BUILD-SNAPSHOT'
	id 'io.spring.dependency-management' version '1.0.8.RELEASE'
	id 'java'
	id 'eclipse'
}

group = 'cloud.test'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = '1.8'

repositories {
	mavenCentral()
	maven { url 'https://repo.spring.io/milestone' }
	maven { url 'https://repo.spring.io/snapshot' }
}

ext {
	set('springCloudVersion', "Hoxton.BUILD-SNAPSHOT")
}

dependencies {
	implementation 'org.springframework.cloud:spring-cloud-starter-gateway'
	
	compileOnly('org.projectlombok:lombok:1.18.2')
	annotationProcessor('org.projectlombok:lombok:1.18.2')
	
	testImplementation('org.springframework.boot:spring-boot-starter-test') {
		exclude group: 'org.junit.vintage', module: 'junit-vintage-engine'
	}
    // This breaks things
    implementation('org.springframework.cloud:spring-cloud-starter-aws-messaging')
}

dependencyManagement {
	imports {
		mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
	}
}

test {
	useJUnitPlatform()
}
```

Nothing much for the main application.
``` java
@SpringBootApplication
public class GatewaytestApplication {

	public static void main(String[] args) {
		SpringApplication.run(GatewaytestApplication.class, args);
	}
	

}
```

**Comment by zhengl7** [comment] 2020-04-07 23:46
Having the exact same issue with `Hoxton.SR3`

**Comment by maciejwalkowiak** [comment] 2020-05-29 21:52
Thanks for reporting. It has been mentioned few times already. Closing as a duplicate of #503.

**Closed by maciejwalkowiak** 2020-05-29 21:52 UTC
Labels: component: sns, status: duplicate, type: bug
