### ISSUE TITLE
SqsMessageDeletionPolicy.ON_SUCCESS deletes a message even if the listener method throws an exception

### ISSUE THREAD

**Issue by jtcotton63** [spring-cloud/spring-cloud-aws#265] opened 2017-09-29 03:42 UTC
According to the [SqsMessageDeletionPolicy.java](https://github.com/spring-cloud/spring-cloud-aws/blob/master/spring-cloud-aws-messaging/src/main/java/org/springframework/cloud/aws/messaging/listener/SqsMessageDeletionPolicy.java) documentation, the ON_SUCCESS does the following:

>  Deletes message when successfully executed by the listener method. If an exception is thrown by the listener method, the message will not be deleted. 

I've noticed that if an exception is thrown before the listener method is invoked (an exception was thrown during the message receipt phase), the message is not deleted. Based on the documentation, that's exactly what I'd expect: no problem there.

The problem is that the message is still deleted even if the listener method throws an exception during execution.

Let me illustrate this better with an example. I have the following code:

````java
@SqsListener(value = "myQueue", deletionPolicy = SqsMessageDeletionPolicy.ON_SUCCESS)
public void listenForAmazonSQS(@NotificationMessage MyObject myObject) {
     LOG.debug("Hello, you made it here");
     throw new RuntimeException("An exception was thrown during the execution of the SQS listener method");
}
````

````java
public class MyObject {
    private String s;
    private int i;

    // Constructors, getters, setters, etc.
}
````

I log into AWS' SQS Management Console and purge all the messages on myQueue. Then I manually put the following message into flight: "This is not JSON and so will fail in the deserialization phase".

Seconds after this message goes into flight, Spring tries to pick it up. This fails since the above string obviously cannot be deserialized into an instance of the MyObject class. Jackson throws an exception before the listener method's code is invoked (you can tell since the log statement never happens), and the message is not deleted from the queue. So far, this is working as expected.

Now I go back to the SQS Management Console, purge the old message, and add the following message to the queue: "{"s": "something", "i": 15}".

Seconds after this new message goes into flight, Spring also tries to pick it up. This time the message is deserialized successfully and the code of the listener method is invoked. The log  statement prints out just fine, but then the exception is thrown. In this case, the message is still being deleted from the queue even tho the exception was thrown during execution of the listener method. I can tell by going back to the SQS Management Console and trying to view any messages in flight. None show up, even if I wait long after the queue's visibility timeout period has passed.

From what the documentation says, the last message should not be deleted from the queue. I would really appreciate this, as a message that fails execution could then be picked up by myQueue's redrive policy and pushed to a dead letter queue.

More relative info:
Using spring cloud starter version Dalston.RELEASE
Using spring cloud aws version 1.2.1.RELEASE

**Comment by maciejwalkowiak** [comment] 2018-05-26 23:52
I am not able to reproduce it with 2.0. Message is not being deleted from the queue and comes back to Spring consumer every X seconds. Once I stop the application message is visible in SQS console.

**Comment by knalx** [comment] 2018-09-25 11:43
Try

`@SqsListener(value = ["myQueue"], deletionPolicy = SqsMessageDeletionPolicy.ON_SUCCESS))`

**Comment by spencergibb** [comment] 2019-01-29 01:37
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem?  It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by spring-issuemaster** [comment] 2019-02-05 01:42
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2019-02-12 01:38
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2019-02-12 01:38 UTC
Labels: feedback-reminder, waiting for feedback
