### ISSUE TITLE
ConditionEvaluationReport is incomplete when used with spring-cloud-starter-aws-parameter-store-config

### ISSUE THREAD

**Issue by fprochazka** [spring-cloud/spring-cloud-aws#511] opened 2019-12-02 22:03 UTC
Hello,
I'm starting a new project and I'm trying to be very careful about what is enabled, therefore I'm consulting the `ConditionEvaluationReport`. But it turns out, that when it's used with `spring-cloud-starter-aws-parameter-store-config`, the report is missing some classes. I've reported it first to spring-boot, but they think it's a spring-cloud issue https://github.com/spring-projects/spring-boot/issues/19212 .

The spring cloud bootstrap process "hijacks" the initialization of the spring context and it initializes only a necessary minimum of dependencies so it can load the properties from aws parameter store. Then it loads the parameters and adds them to the "main" context which is then enabled to continue initializing.

The "cloud" context prints one report and then the "main" context prints another one. I've observed the "cloud" context to be incomplete.

<details>
 <summary>The `report` property is first initialized here</summary>

```
"main@1" prio=5 tid=0x1 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener.initialize(ConditionEvaluationReportLoggingListener.java:86)
	  at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:626)
	  at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:370)
	  at org.springframework.boot.SpringApplication.run(SpringApplication.java:314)
	  at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:140)
	  - locked <0x1286> (a java.util.concurrent.atomic.AtomicBoolean)
	  at org.springframework.cloud.bootstrap.BootstrapApplicationListener.bootstrapServiceContext(BootstrapApplicationListener.java:203)
	  at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:114)
	  at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:71)
	  at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	  at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	  at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	  at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127)
	  at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:76)
	  at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:53)
	  at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:345)
	  at org.springframework.boot.SpringApplication.run(SpringApplication.java:308)
	  at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:140)
	  - locked <0x1287> (a java.util.concurrent.atomic.AtomicBoolean)
	  at com.cogvio.ConsoleApplication.main(ConsoleApplication.java:47)
```

</details>

<details>
 <summary>later, the report is logged from here</summary>

```
"main@1" prio=5 tid=0x1 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener.logAutoConfigurationReport(ConditionEvaluationReportLoggingListener.java:126)
	  at org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener.logAutoConfigurationReport(ConditionEvaluationReportLoggingListener.java:104)
	  at org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener.onApplicationEvent(ConditionEvaluationReportLoggingListener.java:94)
	  at org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener$ConditionEvaluationReportListener.onApplicationEvent(ConditionEvaluationReportLoggingListener.java:164)
	  at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	  at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	  at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	  at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:403)
	  at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:360)
	  at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:897)
	  at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:553)
	  - locked <0x17ac> (a java.lang.Object)
	  at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747)
	  at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	  at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	  at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:140)
	  - locked <0x1286> (a java.util.concurrent.atomic.AtomicBoolean)
	  at org.springframework.cloud.bootstrap.BootstrapApplicationListener.bootstrapServiceContext(BootstrapApplicationListener.java:203)
	  at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:114)
	  at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:71)
	  at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	  at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	  at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	  at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127)
	  at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:76)
	  at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:53)
	  at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:345)
	  at org.springframework.boot.SpringApplication.run(SpringApplication.java:308)
	  at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:140)
	  - locked <0x1287> (a java.util.concurrent.atomic.AtomicBoolean)
	  at com.cogvio.ConsoleApplication.main(ConsoleApplication.java:47)
```

</details>

I'm registering the classes using `META-INF/spring.factories` and I've verified that they in fact are correctly registered and executed

```properties
org.springframework.cloud.bootstrap.BootstrapConfiguration=\
com.cogvio.config.AWSCredentialsConfiguration,\
com.cogvio.config.AWSSimpleSystemsManagementConfiguration

org.springframework.boot.autoconfigure.EnableAutoConfiguration=\
com.cogvio.config.AWSCredentialsConfiguration,\
com.cogvio.config.AWSSimpleSystemsManagementConfiguration
```

<details>
 <summary>AWSSimpleSystemsManagementConfiguration.java</summary>

```java
package com.cogvio.config;

import com.amazonaws.auth.AWSCredentialsProvider;
import com.amazonaws.regions.Regions;
import com.amazonaws.services.simplesystemsmanagement.AWSSimpleSystemsManagement;
import com.amazonaws.services.simplesystemsmanagement.AWSSimpleSystemsManagementClientBuilder;
import org.springframework.boot.autoconfigure.AutoConfigureAfter;
import org.springframework.boot.autoconfigure.AutoConfigureBefore;
import org.springframework.cloud.aws.autoconfigure.paramstore.AwsParamStoreBootstrapConfiguration;
import org.springframework.cloud.aws.core.region.RegionProvider;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Import;

@Configuration
@Import({
    AWSCredentialsConfiguration.class,
})
@AutoConfigureAfter(AWSCredentialsConfiguration.class)
@AutoConfigureBefore(AwsParamStoreBootstrapConfiguration.class)
public class AWSSimpleSystemsManagementConfiguration
{

    @Bean
    public AWSSimpleSystemsManagement ssmClient(
        final AWSCredentialsProvider credentialsProvider,
        final RegionProvider awsRegionProvider
    )
    {
        return AWSSimpleSystemsManagementClientBuilder.standard()
            .withCredentials(credentialsProvider)
            .withRegion(Regions.fromName(awsRegionProvider.getRegion().getName()))
            .build();
    }

}
```

</details>

I would expect the configuration class to be listed in the `Unconditional classes:` section, but it's not, even through it's executed (verified with debugger).

Another note: without the `org.springframework.boot.autoconfigure.EnableAutoConfiguration` section in `META-INF/spring.factories`, the configuration classes are not listed in the `Unconditional classes:` section of the second report.

-----

The reason I'm overriding this configuration is that I want to have better control over how the credentials are loaded. The autodetection is too magic and IMHO too dangerous so I'm turning it off with this.

-----

Relevant libraries & versions

* `org.springframework.boot:spring-boot-starter:jar:2.2.1.RELEASE`
* `org.springframework.cloud:spring-cloud-starter-aws:jar:2.1.2.RELEASE`
* `org.springframework.cloud:spring-cloud-starter-aws-parameter-store-config:jar:2.1.2.RELEASE`

**Comment by maciejwalkowiak** [comment] 2020-06-04 13:29
Tell me I got it right - the issue is that configuration provided for bootstrap phase is not present in Boot's autoconfiguration report? 

If that's the case it's not an issue in Spring Cloud AWS but rather in Boot or Spring Cloud Commons.

**Comment by maciejwalkowiak** [comment] 2020-06-04 14:39
Thanks. Then it looks indeed like a Spring Cloud issue. Perhaps @spencergibb wants.to take a look at it. I'm closing it here as we can't do much in a scope of Spring Cloud AWS

**Closed by maciejwalkowiak** 2020-06-04 14:39 UTC
Labels: component: parameter-store, status: waiting-for-feedback
