### ISSUE TITLE
Peak of requests towards sqs queue observed in case of exception

### ISSUE THREAD

**Issue by netbuilder-it** [spring-cloud/spring-cloud-aws#555] opened 2020-05-22 15:40 UTC
**Describe the bug**
we are using spring cloud version 2.2.1.RELEASE
We have implemented a simple annotated sqs listener  like this:

```
@SqsListener(value = "${param.queue}", deletionPolicy = SqsMessageDeletionPolicy.ON_SUCCESS)
    public void handleMessages(String payload) {
        logger.debug("Original payload: {}", payload);
   ....
```

We noticed that, when the listener raises an exception, a peak of requests towards the Sqs queue are issued, and our instance starts consuming memory and cpu resources

**Sample**
Unfortunately I can't provide a sample ...

**Comment by maciejwalkowiak** [comment] 2020-06-04 12:02
Do you mean exception thrown inside `@SqsListener` annotated method? Are you able to turn on logging to see what kind of requests are issued?

**Comment by netbuilder-it** [comment] 2020-06-04 13:43
Yes I mean exactly an exception in the @SqsListener annotated method.
Unfortunately we have problems or "rate exceeded limit" on CloudWatch and we can't raise the log level... for now we have simply placed a sleep in our code when an exception occurs, to alleviate the issue..

**Comment by maciejwalkowiak** [comment] 2020-06-04 14:00
Assuming you don't have any specific exception handler for this type of exception, Spring Cloud AWS behaviour is to apply deletion policy when error occurs. If Spring Cloud AWS is meant to delete the message it executes `deleteMessageAsync` using `AmazonSQSAsync` from AWS SDK. This call can be retried by the SDK itself if it fails but I don't see a place where Spring Cloud AWS itself could trigger peak of requests. I am also not able to reproduce it. 

I will close it for now but you are welcome to come back with more details and ideally code that can reproduce this issue. I would be happy to investigate it further then.

**Closed by maciejwalkowiak** 2020-06-04 14:00 UTC
Labels: component: sqs, status: waiting-for-feedback
