### ISSUE TITLE
Grails 3.1.6 War file deployment issue in Tomcat 7 & 8. When i tried to deploy a war file in tomcat server i got the below error:

### ISSUE THREAD

**Issue by pavithraNovember** [spring-cloud/spring-cloud-aws#178] opened 2016-10-19 10:07 UTC

**Comment by pavithraNovember** [comment] 2016-10-19 10:11
When i tried t deploy a war file in tomcat server 7 i got the below error:
Sep 25, 2016 11:09:05 PM org.apache.catalina.startup.HostConfig deployWAR
INFO: Deployment of web application archive /home/cimwebadm/tomcat_instances/Tomcat-instance/webapps/myapp.war has finished in 3,903 ms
Sep 25, 2016 11:09:05 PM org.apache.catalina.startup.HostConfig deployWAR
INFO: Deploying web application archive /home/cimwebadm/tomcat_instances/cien-grails/webapps/myapp.war
Sep 25, 2016 11:09:06 PM org.apache.catalina.loader.WebappClassLoader validateJarFile
INFO: validateJarFile(/home/cimwebadm/tomcat_instances/cien-grails/webapps/cien-0.1/WEB-INF/lib/tomcat-embed-core-8.0.32.jar) - jar not loaded. See Servlet Spec 3.0, section 10.7.2. Offending class: javax/servlet/Servlet.class
Sep 25, 2016 11:09:06 PM org.apache.catalina.loader.WebappClassLoader validateJarFile
INFO: validateJarFile(/home/cimwebadm/tomcat_instances/cien-grails/webapps/cien-0.1/WEB-INF/lib/tomcat-embed-el-8.0.32.jar) - jar not loaded. See Servlet Spec 3.0, section 10.7.2. Offending class: javax/el/Expression.class
Sep 25, 2016 11:09:06 PM org.apache.catalina.deploy.WebXml setVersion
WARNING: Unknown version string [3.1]. Default version will be used.
Sep 25, 2016 11:09:13 PM org.apache.catalina.core.ContainerBase addChildInternal
SEVERE: ContainerBase.addChild: start: 
org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[az84cimap02.am.freescale.net].StandardContext[/cien-0.1]]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:154)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:649)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1081)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1877)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodError: javax.servlet.ServletContext.getVirtualServerName()Ljava/lang/String;
	at org.apache.tomcat.websocket.server.WsServerContainer.<init>(WsServerContainer.java:149)
	at org.apache.tomcat.websocket.server.WsSci.init(WsSci.java:131)
	at org.apache.tomcat.websocket.server.WsSci.onStartup(WsSci.java:47)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5481)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	... 10 more

Sep 25, 2016 11:09:13 PM org.apache.catalina.startup.HostConfig deployWAR
SEVERE: Error deploying web application archive /home/cimwebadm/tomcat_instances/cien-grails/webapps/myapp.war
java.lang.IllegalStateException: ContainerBase.addChild: start: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[az84cimap02.am.freescale.net].StandardContext[/cien-0.1]]
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:904)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:649)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1081)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1877)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by artembilan** [comment] 2016-10-19 13:27
Excuse me, how does this relate to [Spring Cloud AWS](http://cloud.spring.io/spring-cloud-aws/)?

**Comment by aemruli** [comment] 2017-02-28 20:30
@pavithraNovember closing for now as there is really not anything we can do. Please re-open with a description if you think that spring-cloud-aws is the cause.

**Closed by aemruli** 2017-02-28 20:30 UTC
