### ISSUE TITLE
MessagingAutoConfiguration hangs for ~25 seconds

### ISSUE THREAD

**Issue by edubkn** [spring-cloud/spring-cloud-aws#344] opened 2018-06-15 19:21 UTC
Hello,

I have a problem in my application when the autoconfiguration is active for aws messaging. So far I am only using SQS listeners and a SNS publisher. The autoconfiguration suits me fine except for this issue that it takes a long time to startup. It hangs exaclty in this line after mapping my queues:
```
[INFO ] [2018-06-15T16:06:06,648] [] [ExecutorConfigurationSupport->initialize:165] | Initializing ExecutorService 
```
I suspect it is something that the autoconfiguration does that I don't really need, because if I overwrite the autoconfiguration it doesn't hangs there for ~25 seconds:
```
@SpringBootApplication
@EnableAutoConfiguration(exclude = {MessagingAutoConfiguration.class})
public class Application {

    public static void main(String[] args) throws Exception {
        SpringApplication.run(Application.class, args);
    }
}
```
```
    @Bean
    public AmazonSQSAsync amazonSQS() {
        return  AmazonSQSAsyncClientBuilder
                .standard()
                .withRegion(Regions.SA_EAST_1)
                .withCredentials(new DefaultAWSCredentialsProviderChain())
                .build();
    }

    @Bean
    public AmazonSNSAsync amazonSNS() {
        return  AmazonSNSAsyncClientBuilder
                .standard()
                .withRegion(Regions.SA_EAST_1)
                .withCredentials(new DefaultAWSCredentialsProviderChain())
                .build();
    }

    @Bean
    public QueueMessageHandler queueMessageHandler() {
        final QueueMessageHandlerFactory queueMsgHandlerFactory = new QueueMessageHandlerFactory();
        queueMsgHandlerFactory.setAmazonSqs(amazonSQS());

        return queueMsgHandlerFactory.createQueueMessageHandler();
    }

    @Bean
    public SimpleMessageListenerContainerFactory simpleMessageListenerContainerFactory() {
        final SimpleMessageListenerContainerFactory msgListenerContainerFactory = new SimpleMessageListenerContainerFactory();
        msgListenerContainerFactory.setAmazonSqs(amazonSQS());
        msgListenerContainerFactory.setMaxNumberOfMessages(5);
        msgListenerContainerFactory.setWaitTimeOut(20);

        return msgListenerContainerFactory;
    }

    @Bean
    public SimpleMessageListenerContainer simpleMessageListenerContainer(final QueueMessageHandler messageHandler,
            final SimpleMessageListenerContainerFactory simpleMessageListenerContainerFactory) {
        final SimpleMessageListenerContainer msgListenerContainer = simpleMessageListenerContainerFactory
                .createSimpleMessageListenerContainer();
        msgListenerContainer.setMessageHandler(messageHandler);

        return msgListenerContainer;
    }
```
This is a very simple/standard messaging configuration so I don't know what could be the problem with the autoconfiguration.
I have three queues configured in listener classes using `@SqsListener`
Does anyone have an idea of the problem?

**Comment by edubkn** [comment] 2018-06-15 19:40
The problem is the `amazonSQS` bean. Just by overriding it I am able to solve the problem.

**Comment by maciejwalkowiak** [comment] 2018-06-15 21:44
Thanks for reporting! I was not able to replicate the issue in my setup. Can you post a complete project in a separate repository that reproduces this issue?

**Comment by spencergibb** [comment] 2019-01-29 02:03
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spencergibb** 2019-01-29 02:03 UTC
Labels: waiting-for-triage
