### ISSUE TITLE
How to configure @MessageMapping handler for two queues from properties

### ISSUE THREAD

**Issue by ulisses79** [spring-cloud/spring-cloud-aws#88] opened 2015-07-23 13:08 UTC
I can configure statical message handler for two queues using annotation @MessageMapping like this MessageMapping({"Q1", "Q2"}), right?

I'd like to provide queues names from the properties file. Test and prod environments have different queues names.
Is it possible?

**Comment by aemruli** [comment] 2015-07-28 14:39
Hi @ulisses79 this should be possible indeed. You can use a property place holder for that. 

Just write @MessageMapping({"${myQueue1}", "${myQueue2}"}), both should resolve to the actual queue names that are defined in your property file. 

I am closing this ticket for now as this is not a bug/feature, please re-open in case you run into troubles.

**Closed** 2015-07-28 14:39 UTC
Labels: question

**Comment by ulisses79** [comment] 2015-07-31 11:34
Thank you, it helped a bit. What if I'd like to provide one property name which is a comma-separated string containing queues names?
myQueues=Q1,Q2....,Qn
something like this
@MessageMapping({"${myQueues}")
