### ISSUE TITLE
profile file cannot be null

### ISSUE THREAD

**Issue by Lone5267** [spring-cloud/spring-cloud-aws#534] opened 2020-03-25 00:04 UTC
**Describe the bug**
I am trying to use SNS to send a message, however, it gives me ERROR.

```
Resolved [com.amazonaws.SdkClientException: Unable to load AWS credentials from any provider in the chain: [com.amazonaws.auth.EC2ContainerCredentialsProviderWrapper@3d572a77: Unable to load credentials from service endpoint, com.amazonaws.auth.profile.ProfileCredentialsProvider@779e33d4: profile file cannot be null]]
```
Even if I have already given the credentials details in my `application.yml` file.
```
cloud:
  aws:
    credentials:
      access-key: AKIXXXXXXXXXXXXXX
      secret-key: TmKrqVXXXXXXXXXXXXXXXXXXXXXXXXXXXX
```
I solved this problem by adding an extra Bean, But I have no idea why my configuration doesn't work? Is there anything I left?
```
    @Bean
    @Primary
    public AWSCredentialsProvider getCredentialsProvider() {
        return new ClasspathPropertiesFileCredentialsProvider();
    }
```
spring-boot version is 2.2.4
spring-cloud version is Hoxton.SR3

**Sample**
Nothing

**Comment by dmile** [comment] 2020-04-03 09:48
https://github.com/spring-cloud/spring-cloud-aws/blob/328b1307f41f8b011a964d7491318e9df6345b17/spring-cloud-aws-autoconfigure/src/main/java/org/springframework/cloud/aws/autoconfigure/context/ContextCredentialsAutoConfiguration.java#L88-L91
Try to rename key properties:
```yaml
cloud:
  aws:
    stack:
      auto: false
    credentials:
      accessKey: "yourAccessKey"
      secretKey: "yourSecretKey"
```

**Comment by maciejwalkowiak** [comment] 2020-05-29 21:01
I second @dmile. At the current stage the right way to set access key and secret key is through camel case version (despite IDE autocompletion suggesting the other way).

Closing as a duplicate of https://github.com/spring-cloud/spring-cloud-aws/issues/535 but this will be fixed for sure.

**Closed** 2020-05-29 21:01 UTC
Labels: status: duplicate
