### ISSUE TITLE
Map "SentTimestamp" to SqsMessageHeaders

### ISSUE THREAD

**Issue by erikpetzold** [spring-cloud/spring-cloud-aws#296] opened 2018-02-02 11:28 UTC
When injecting `MessageHeaders` into a method annotated with `@SqsListener`, then in these headers the timestamp is missing.

Calling `headers.getTimestamp()` returns null. In the message from SQS there are the properties "SentTimestamp" and "ApproximateFirstReceiveTimestamp" available.

Would be nice if "SentTimestamp" was mapped into "timestamp" when creating `MessageHeaders`. 

Otherwise would be also possible to add specific getters for the two different timestamp properties to `SqsMessageHeaders`. But at the moment it seems not possible to inject `SqsMessageHeaders` into the method, only `MessageHeaders`.

**Comment by voytech** [comment] 2020-06-06 13:51
Can I look at this one?

**Comment by maciejwalkowiak** [comment] 2020-06-06 13:56
@voytech go for it!

**Comment by voytech** [comment] 2020-06-08 08:30
@maciejwalkowiak  @erikpetzold  

The problem with null value in `timestamp` in MessageHeaders occurs when dispatching a message to handler. It is because there is a need of enriching existing  MessageHeaders with **lookupDestination** header. For that purpose MessageHeadersAccessor is used internally. MessageHeaderAccessors after adding new header, creates its own implementation of MessageHeaders -  `**MessageHeaderAccessor.MutableMessageHeaders**`, and this is runtime object which is always present in @SqsListener method. MessageHeaderAccessor is implemented in such a way that it makes ID and TIMESTAMP always nulls - it is because it is creating new MessageHeaders object, and its seems to be designed in such a way that ID and TIMESTAMP are meant to be tightly connected with SINGLE immutable instance of an MessageHeaders, that is why timestamp is always null. Looking at the code it can be also set to new current timestamp value, but never can contain original, externally provided timestamp.  

**So the question is, if timestamp header is designed to keep such external property like e.g. 'SentTimestamp', or by design it should contain a current time when MessageHeaders where instantiated ? If this is not the case, and If it should be possible to pass external value as timestamp - so this seems to be issue witch spring-messaging and the way how MessageHeadersAccessor works**
   
> Otherwise would be also possible to add specific getters for the two different timestamp properties to SqsMessageHeaders. But at the moment it seems not possible to inject SqsMessageHeaders into the method, only MessageHeaders.

Nevertheless I see following solutions for above:
1. Writing custom **MethodArgumentResolver** supporting SqsMessageHeaders as parameter to SqsListener handler method, and map runtime **MessageHeaderAccessor.MutableMessageHeaders** to new SqsMessageHeaders with timestamp populated from **SentTimestamp** and additionally providing convenient getters for ApproximateFirstReceiveTimestamp, and ApproximateReceiveCount.

2. Switching from AbstractMethodMessageHandler.handleMessage (which internally uses **MessageHeaderAccessor**)  - and creating new method (say - handleSqsMessage in QueueMessageHandler) which instead of using **MessageHeaderAccessor** will create SqsMessageHeaders instance directly. This solution makes handleMessage from AbstractMethodMessageHandler unused, and introduces sibling method with same responsibility (without MessageHeaderAccessor) in QueueMessageHandler - I think bad design. Also I think that I may not know everything about rationale for presence of MessageHeaderAccessor in here. It seems to be here for real reason, maybe it should be required for @SqsListener handler method to always have runtime type MessageHeaderAccessor.MutableMessageHeaders for consumers?

**Comment by voytech** [comment] 2020-06-08 09:35
I think that more acceptable solution is first one, as long as this approach utilizes MethodArgumentResolvers, so I think we are using things the way they are designed to be used. It is not workaround (like second solution), It is just framework way of resolving arguments. 

But still the question is.. Is it good to use timestamp header to hold external SentTimestamp which is timestamp the massage was sent to the queue ?

**Comment by voytech** [comment] 2020-06-15 19:15
@maciejwalkowiak I have created pull request for this one here - https://github.com/spring-cloud/spring-cloud-aws/pull/584.  I see that there are plans to rewrite sqs integration, so not sure if this pull request is still valid. 

I have also a little concern if this change should be allowed to go with ‚minor’ version change - it is enchancement which doesn’t break compile time backward compatibility, but changes runtime object injected as MessageHeaders (it is now SqsMessageHeaders).

Please let me know if you are going to review (If you want different approach I can also change implementation), or otherwise close. ;)

**Comment by maciejwalkowiak** [comment] 2020-06-16 04:58
Hey @voytech! I had a quick look and I'll do deeper review this week. SQS is going to change but hopefully only internally and API remains the same. Your changes look good and if they are breaking they will just go with 2.3. But let me spend one evening with them first ;)

**Closed** 2020-06-18 22:36 UTC
Labels: component: sqs, status: in-progress, type: enhancement
