### ISSUE TITLE
Message Deletion - Policy Feedback

### ISSUE THREAD

**Issue by forbode** [spring-cloud/spring-cloud-aws#223] opened 2017-05-03 03:47 UTC
**The problem**
When the SQS Policy for a Queue does not allow for "DeleteMessage" Spring Cloud AWS fails to delete the message, which causes the visibility to timeout, which causes the message to be processed again. 

The main issue is that _there is no feedback that the message deletion failed._ 

Yes, this is an issue caused by poor policy writing, but it would be helpful to provide logging indicating failure. 

**Possible Solution**
I can see that the SimpleMessageListenerContainer uses the async SQS client. The "deleteMessageAsync" call returns a future that can be examined for success. Right now it is not (the overhead on this should be minimal).

**Comment by alainsahli** [comment] 2017-05-20 08:06
Hi @forbode 

Good point, we're going to add some logging message.

**Comment by maciejwalkowiak** [comment] 2020-05-29 22:34
Closing as a duplicate of #539

**Closed by maciejwalkowiak** 2020-05-29 22:34 UTC
Labels: component: sqs, type: bug
