### ISSUE TITLE
Access denied when using springboot-cloud-aws-context on eks with service iam role

### ISSUE THREAD

**Issue by aavileli** [spring-cloud/spring-cloud-aws#538] opened 2020-04-04 00:00 UTC
Access denied when using springboot-cloud-aws-context on eks with service iam role

The AWS SDKs have been updated with a new credential provider that calls sts:AssumeRoleWithWebIdentity, exchanging the Kubernetes-issued OIDC token for AWS role credentials. We cannot use the latest 2.2.2 springboot-cloud-aws-context as the aws sdk version in the depenedency is using version 1.11.415 which does not have this new credential provider.

Please update springboot-cloud-aws package in public maven so we can use this package from upstream

Minimum version required for this to work 1.11.704.

Also in the spring cloud aws sdk dependency you need to include com.amazonaws:aws-java-sdk-sts

Ref:: https://github.com/aws/aws-sdk-java/commit/1322472c350d07fa2355c110bc023afda6a4cc3b#diff-9ec57c5c3661faef6151e409625637e6

Also on aws eks the pods have been disabled from accessing the metadata service

**Comment by patalwell** [comment] 2020-05-07 16:28
+1 Might also want to consider supporting Java SDK V2; which will take care of the credentials chain issues and future depreciation of Java SDK V1.

**Comment by maciejwalkowiak** [comment] 2020-05-29 20:46
Thanks @aavileli for reporting.

As a temporary workaround take a look please at: https://github.com/spring-cloud/spring-cloud-aws/issues/482#issuecomment-636145974

I am closing this one as a duplicate of #482 as the underlying problem is the same.

**Closed** 2020-05-29 20:46 UTC
Labels: status: duplicate, type: dependency-upgrade
