### ISSUE TITLE
SNS notification message object not getting deserialized

### ISSUE THREAD

**Issue by sidgate** [spring-cloud/spring-cloud-aws#360] opened 2018-07-23 08:45 UTC
Bug report

This seems to similar to https://github.com/spring-projects/spring-integration-aws/issues/39

By default the MappingJackson2HttpMessageConverter's supported media type is application/json, but SNS notifications are in text/plain (even though they send perfectly correct JSON).

    @NotificationMessageMapping
       public void xxx(@NotificationSubject String subject, @NotificationMessage Student student) {
        //
       }

Getting following exception for valid JSON

```
c.a.common.SpringRestErrorHandler        : Fatal system error occured
org.springframework.http.converter.HttpMessageNotReadableException: Error converting notification message with payload:{
 ...
}
        at org.springframework.cloud.aws.messaging.endpoint.NotificationMessageHandlerMethodArgumentResolver.doResolveArgumentFromNotificationMessage(NotificationMessageHandlerMethodArgumentResolver.java:79) ~[spring-cloud-aws-messaging-2.0.0.RELEASE.jar!/:2.0.0.RELEASE]
        at org.springframework.cloud.aws.messaging.endpoint.AbstractNotificationMessageHandlerMethodArgumentResolver.resolveArgument(AbstractNotificationMessageHandlerMethodArgumentResolver.java:54) ~[spring-cloud-aws-messaging-2.0.0.RELEASE.jar!/:2.0.0.RELEASE]

```

```
"content-type": [
"text/plain; charset=UTF-8"
]
```

**Comment by nmlynch94** [comment] 2018-07-25 21:14
We are seeing this as well

**Comment by ShevaDavid** [comment] 2018-09-01 14:56
@sidgate use **contentType** attribute with **application/json** value
![image](https://user-images.githubusercontent.com/17084031/44947086-4aa77b80-ae10-11e8-8348-cf5dab778a8a.png)

**Comment by spencergibb** [comment] 2019-01-29 02:21
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem?  It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by spring-issuemaster** [comment] 2019-02-12 02:23
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2019-02-12 02:23 UTC
Labels: feedback-reminder, waiting for feedback

**Comment by Kernelogy** [comment] 2021-12-04 06:24
By disabling the "Raw Message Delivery" in topic subscription created, the issue could be rectified.
