### ISSUE TITLE
Upgrade to version 2 of the Amazon SDK

### ISSUE THREAD

**Issue by gpmind** [spring-cloud/spring-cloud-aws#520] opened 2020-02-04 16:45 UTC
**Describe the bug**
The amazon api endpoints have started warning about potential problems with using libraries coming from version 1 of the api. That's com.amazonaws:aws-... We can not use both revision of the API at the same time, there are numerous conflicts that arise from Spring Cloud dependencies starting with having 2 different SdkClientException classes to deal with.

**Sample**
You can make any standard test with asynchronous clients and you should get the mail.

**Comment by raoofm** [comment] 2020-02-13 17:27
duplicate of #267 ?

**Comment by gpmind** [comment] 2020-02-14 19:43
It certainly looks like it, and it's been hanging since 2016?

**Comment by maciejwalkowiak** [comment] 2020-05-29 21:29
Indeed it's a duplicate of #267. You should be able to use SDK v1 and v2 in the same project.

**Closed by maciejwalkowiak** 2020-05-29 21:29 UTC
Labels: status: waiting-for-triage
